version: 1
accounts:
  - name: alice
    coins:
      - 20000token
      - 200000000stake
  - name: bob
    coins:
      - 10000token
      - 10000foocoin
      - 100000000stake
  - name: frank
    coins:
      - 10000token
      - 100000000stake
      - 10000foocoin
    mnemonic: chuckle tube pave draft stereo cotton brisk grocery require soft brother lemon
faucet:
  name: bob
  coins:
    - 5token
    - 100000stake
client:
  typescript:
    path: ts-client
  composables:
    path: vue/src/composables
  hooks:
    path: react/src/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
  - name: alice
    bonded: 100000000stake
